
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
 
use_frameworks!
# inhibit_all_warnings!

target 'OCWithFlutter' do
 flutter_application_path = '../flutter_module'
 load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
install_all_flutter_pods(flutter_application_path)
end



